# Generated by Django 3.0.8 on 2020-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0002_auto_20200709_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.IntegerField(),
        ),
    ]
