# Generated by Django 3.0.8 on 2020-07-09 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0003_auto_20200709_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='seconds_after_midnight',
            new_name='minutes_after_midnight',
        ),
    ]
