# Generated by Django 3.0.8 on 2020-07-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0005_auto_20200709_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='minutes_after_midnight',
            field=models.IntegerField(),
        ),
    ]
