# Generated by Django 3.0.8 on 2020-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseInterface', '0007_activity_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.CharField(default='user', max_length=250),
        ),
    ]
